/*
export const REQ_TO_UPLOAD_FILE = 'REQ_TO_UPLOAD_FILE';
export const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS';
export const FILE_UPLOAD_FAILURE = 'FILE_UPLOAD_FAILURE';
export const REQ_TO_ENCRYPT = 'REQ_TO_ENCRYPT';
export const ENCRYPT_SUCCESS = 'ENCRYPT_SUCCESS';
export const ENCRYPT_FAILURE = 'ENCRYPT_FAILURE';
export const REQ_TO_DECRYPT = 'REQ_TO_DECRYPT';
export const DECRYPT_SUCCESS = 'DECRYPT_SUCCESS';
export const DECRYPT_FAILURE = 'DECRYPT_FAILURE';
export const SWITCH_LANGUAGE = 'SWITCH_LANGUAGE';
*/
export enum actionTypes {
  REQ_TO_UPLOAD_FILE = "REQ_TO_UPLOAD_FILE",
  FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS',
  FILE_UPLOAD_FAILURE = 'FILE_UPLOAD_FAILURE',
  REQ_TO_ENCRYPT = 'REQ_TO_ENCRYPT',
  ENCRYPT_SUCCESS = 'ENCRYPT_SUCCESS',
  ENCRYPT_FAILURE = 'ENCRYPT_FAILURE',
  REQ_TO_DECRYPT = 'REQ_TO_DECRYPT',
  DECRYPT_SUCCESS = 'DECRYPT_SUCCESS',
  DECRYPT_FAILURE = 'DECRYPT_FAILURE',
  SWITCH_LANGUAGE = 'SWITCH_LANGUAGE',
}
